version: 2.1
orbs:
  node: circleci/node@10.16.3
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: node_modules/.bin/gulp textlint 
workflows:
    build-and-test:
      jobs:
        - build-and-test